import Link from "next/link";
import { SanityImage } from "@/components/sanity-image";
import { contentPillars } from "@/lib/content-pillars";
import { isSanityConfigured } from "@/sanity/env";
import { client } from "@/sanity/lib/client";
import { FEATURED_ARTICLE_QUERY, NEWSROOM_QUERY } from "@/sanity/lib/queries";

type Article = { _id: string; title: string; subtitle?: string; slug: string; pillar: string; publishedAt?: string; readingMinutes?: number; author?: { name: string }; coverImage?: { alt?: string; asset?: { metadata?: { lqip?: string } } } };
function Card({ article, large = false }: { article: Article; large?: boolean }) { return <Link href={`/news/${article.slug}`} className="group block"><div className={`overflow-hidden rounded-[1.5rem] bg-gradient-to-br from-indigo-600 via-violet-500 to-sky-400 ${large ? "aspect-[16/9]" : "aspect-[16/10]"}`}>{article.coverImage?.asset ? <SanityImage value={article.coverImage} width={large ? 1440 : 800} height={large ? 810 : 560} className="h-full w-full object-cover transition group-hover:scale-[1.02]" priority={large} /> : null}</div><p className="mt-4 text-xs font-semibold uppercase tracking-[.22em] text-indigo-600">{article.pillar}</p><h3 className={`${large ? "text-3xl sm:text-4xl" : "text-xl sm:text-2xl"} mt-3 font-semibold leading-[1.1] tracking-[-.035em] text-slate-950 group-hover:text-indigo-700`}>{article.title}</h3>{article.subtitle ? <p className="mt-3 text-sm leading-6 text-slate-600">{article.subtitle}</p> : null}<p className="mt-4 text-sm text-slate-500">{article.readingMinutes ? `${article.readingMinutes} min read` : "Read article"}</p></Link>; }

export default async function NewsPage() {
  let articles: Article[] = [], featured: Article | null = null;
  if (isSanityConfigured) [articles, featured] = await Promise.all([client.fetch(NEWSROOM_QUERY) as Promise<Article[]>, client.fetch(FEATURED_ARTICLE_QUERY) as Promise<Article | null>]);
  const displayFeatured = featured || articles[0];
  const latest = articles.filter((article) => article._id !== displayFeatured?._id).slice(0, 4);
  return <main className="px-6 py-9 sm:px-8 lg:px-10 lg:py-12"><div className="mx-auto max-w-7xl">
    <section className="border-b border-slate-200 pb-10"><p className="text-xs font-semibold uppercase tracking-[.32em] text-indigo-600">Back to Protocol / Newsroom</p><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="max-w-3xl text-4xl font-semibold tracking-[-.045em] text-slate-950 sm:text-6xl">The signal for a healthier, more capable life.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Evidence-led reporting across the eight systems that move health forward.</p></div><Link href="/articles" className="inline-flex w-fit rounded-full bg-slate-950 px-5 py-3 text-sm font-medium text-white hover:bg-indigo-700">Browse all articles</Link></div></section>
    <nav className="flex gap-6 overflow-x-auto border-b border-slate-200 py-5 text-sm font-medium whitespace-nowrap text-slate-600">{contentPillars.map((item) => <Link key={item.name} href={`/articles?pillar=${encodeURIComponent(item.name)}`} className="hover:text-indigo-600">Explore {item.name}</Link>)}</nav>
    {displayFeatured ? <section className="py-12"><div className="mb-6 flex items-baseline justify-between"><p className="text-xs font-semibold uppercase tracking-[.25em] text-slate-500">Featured coverage</p><Link href="/articles" className="text-sm font-medium text-indigo-600 hover:text-slate-950">All articles</Link></div><div className="grid gap-10 xl:grid-cols-[minmax(0,1.2fr)_minmax(15rem,.6fr)]"><Card article={displayFeatured} large /><aside className="border-t border-slate-900 pt-4 xl:border-t-0 xl:border-l xl:pl-7"><h2 className="text-2xl font-semibold tracking-tight text-slate-950">Latest news</h2><div className="mt-4 divide-y divide-slate-200 border-t border-slate-900">{latest.map((article) => <Link key={article._id} href={`/news/${article.slug}`} className="block py-5 group"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-indigo-600">{article.pillar}</p><h3 className="mt-2 text-base font-semibold leading-5 text-slate-950 group-hover:text-indigo-700">{article.title}</h3></Link>)}</div></aside></div></section> : <p className="py-12 text-slate-600">Published articles will appear here soon.</p>}
    <section className="border-t border-slate-200">{contentPillars.map((pillar) => { const items = articles.filter((article) => article.pillar === pillar.name).slice(0, 3); return <div key={pillar.name} className="grid gap-8 border-b border-slate-200 py-10 lg:grid-cols-[14rem_minmax(0,1fr)]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-indigo-600">{pillar.name}</p><p className="mt-3 text-sm leading-6 text-slate-600">{pillar.definition}</p><Link href={`/articles?pillar=${encodeURIComponent(pillar.name)}`} className="mt-5 inline-block text-sm font-medium text-slate-950 hover:text-indigo-700">Explore {pillar.name} →</Link></div>{items.length ? <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{items.map((article) => <Card key={article._id} article={article} />)}</div> : <p className="text-sm text-slate-500">New reporting coming soon.</p>}</div>; })}</section>
  </div></main>;
}
