-- Supabase representation of the Amazon Excel workbook.
alter table public.amazon_products
  add column if not exists store text,
  add column if not exists availability text,
  add column if not exists affiliate_link text,
  add column if not exists last_scraped timestamptz,
  add column if not exists category_path text[];

create table if not exists public.amazon_product_categories (
  id bigint generated by default as identity primary key,
  asin text not null references public.amazon_products(asin) on delete cascade,
  category_level integer not null,
  category text not null,
  unique (asin, category_level)
);

create table if not exists public.amazon_product_bullets (
  id bigint generated by default as identity primary key,
  asin text not null references public.amazon_products(asin) on delete cascade,
  bullet_number integer not null,
  bullet_point text not null,
  unique (asin, bullet_number)
);

create table if not exists public.amazon_product_attributes (
  id bigint generated by default as identity primary key,
  asin text not null references public.amazon_products(asin) on delete cascade,
  attribute text not null,
  value text not null,
  unique (asin, attribute)
);

create table if not exists public.amazon_product_images (
  id bigint generated by default as identity primary key,
  asin text not null references public.amazon_products(asin) on delete cascade,
  image_number integer not null,
  image_url text not null,
  unique (asin, image_number)
);

create table if not exists public.amazon_product_variations (
  id bigint generated by default as identity primary key,
  asin text not null references public.amazon_products(asin) on delete cascade,
  variation_number integer not null,
  variation text not null,
  unique (asin, variation_number)
);

create table if not exists public.amazon_product_price_history (
  id bigint generated by default as identity primary key,
  asin text not null references public.amazon_products(asin) on delete cascade,
  recorded_at timestamptz not null,
  price numeric
);

create table if not exists public.amazon_product_scrape_log (
  id bigint generated by default as identity primary key,
  asin text references public.amazon_products(asin) on delete cascade,
  logged_at timestamptz not null,
  field text not null,
  status text not null,
  message text not null
);

create index if not exists amazon_product_categories_asin_idx on public.amazon_product_categories(asin);
create index if not exists amazon_product_bullets_asin_idx on public.amazon_product_bullets(asin);
create index if not exists amazon_product_attributes_asin_idx on public.amazon_product_attributes(asin);
create index if not exists amazon_product_images_asin_idx on public.amazon_product_images(asin);
create index if not exists amazon_product_variations_asin_idx on public.amazon_product_variations(asin);
create index if not exists amazon_product_price_history_asin_idx on public.amazon_product_price_history(asin);
create index if not exists amazon_product_scrape_log_asin_idx on public.amazon_product_scrape_log(asin);

alter table public.amazon_product_categories enable row level security;
alter table public.amazon_product_bullets enable row level security;
alter table public.amazon_product_attributes enable row level security;
alter table public.amazon_product_images enable row level security;
alter table public.amazon_product_variations enable row level security;
alter table public.amazon_product_price_history enable row level security;
alter table public.amazon_product_scrape_log enable row level security;

drop policy if exists "Public can read product categories" on public.amazon_product_categories;
drop policy if exists "Public can read product bullets" on public.amazon_product_bullets;
drop policy if exists "Public can read product attributes" on public.amazon_product_attributes;
drop policy if exists "Public can read product images" on public.amazon_product_images;
drop policy if exists "Public can read product variations" on public.amazon_product_variations;
drop policy if exists "Public can read product price history" on public.amazon_product_price_history;
drop policy if exists "Public can read product scrape log" on public.amazon_product_scrape_log;

create policy "Public can read product categories" on public.amazon_product_categories for select using (true);
create policy "Public can read product bullets" on public.amazon_product_bullets for select using (true);
create policy "Public can read product attributes" on public.amazon_product_attributes for select using (true);
create policy "Public can read product images" on public.amazon_product_images for select using (true);
create policy "Public can read product variations" on public.amazon_product_variations for select using (true);
create policy "Public can read product price history" on public.amazon_product_price_history for select using (true);
create policy "Public can read product scrape log" on public.amazon_product_scrape_log for select using (true);
