import Link from "next/link";
import { ArrowLeft, Check, Cloud, KeyRound } from "lucide-react";
import { ProcurementQuoteForm } from "@/components/procurement-quote-form";

export const metadata = { title: "Request a Software Quote | Back to Protocol", description: "Request a professional software licensing, implementation, security, and support quote." };

export default function SoftwareQuotePage() {
  return <main className="min-h-screen bg-[#f6f7f2] px-5 py-10 text-[#17211b] sm:px-8 lg:px-12 lg:py-16"><div className="mx-auto max-w-[1100px]"><Link href="/software" className="inline-flex items-center gap-2 text-sm text-[#607067] hover:text-[#1f7a4d]"><ArrowLeft className="h-4 w-4" /> Back to software procurement</Link><div className="mt-10 grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-start"><div><div className="flex h-12 w-12 items-center justify-center bg-[#17211b] text-[#9dd9b7]"><Cloud className="h-6 w-6" /></div><p className="mt-7 text-xs font-bold uppercase text-[#1f7a4d]">Software quote</p><h1 className="mt-3 font-serif text-5xl leading-tight sm:text-6xl">Let&apos;s build the right software plan.</h1><p className="mt-5 text-lg leading-8 text-[#5a685f]">Tell us about your users, tools, licensing needs, and goals. We&apos;ll prepare a practical quote for the software and implementation work.</p><div className="mt-8 space-y-4 border-t border-[#17211b]/15 pt-6 text-sm leading-6 text-[#607067]">{["Compare plans, seats, and licensing", "Look for available business pricing", "Include migration, security, and onboarding", "Plan for renewals and ongoing support"].map((item) => <p key={item} className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#1f7a4d]" />{item}</p>)}</div><p className="mt-8 flex gap-3 text-sm leading-6 text-[#607067]"><KeyRound className="mt-0.5 h-5 w-5 shrink-0 text-[#1f7a4d]" />We treat permissions, recovery, and security as part of the implementation.</p></div><ProcurementQuoteForm kind="software" /></div></div></main>;
}
