import Link from "next/link";
import { SanityImage } from "@/components/sanity-image";
import { contentPillars } from "@/lib/content-pillars";
import { isSanityConfigured } from "@/sanity/env";
import { client } from "@/sanity/lib/client";
import { FILTERED_ARTICLES_COUNT_QUERY, FILTERED_ARTICLES_QUERY, NEWSROOM_AUTHORS_QUERY } from "@/sanity/lib/queries";

type Article = { _id: string; title: string; subtitle?: string; slug: string; pillar: string; publishedAt?: string; author?: { name: string }; coverImage?: { alt?: string; asset?: { metadata?: { lqip?: string } } } }; type Author = { _id: string; name: string }; const perPage = 9;
function Card({ article }: { article: Article }) { return <Link href={`/news/${article.slug}`} className="group block"><div className="aspect-[16/10] overflow-hidden rounded-2xl bg-gradient-to-br from-indigo-600 via-violet-500 to-sky-400">{article.coverImage?.asset ? <SanityImage value={article.coverImage} width={900} height={560} className="h-full w-full object-cover transition group-hover:scale-[1.02]" /> : null}</div><p className="mt-4 text-xs font-semibold uppercase tracking-[.2em] text-indigo-600">{article.pillar}</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-slate-950 group-hover:text-indigo-700">{article.title}</h2><p className="mt-3 text-sm text-slate-500">{article.author?.name || "Back to Protocol Editorial"}</p></Link>; }
export default async function ArticlesPage({ searchParams }: { searchParams: Promise<{ pillar?: string; author?: string; page?: string }> }) { const params = await searchParams; const pillar = contentPillars.some((item) => item.name === params.pillar) ? params.pillar : undefined; const author = params.author || undefined; const page = Math.max(1, Number.parseInt(params.page || "1", 10) || 1); const start = (page - 1) * perPage; let articles: Article[] = [], authors: Author[] = [], total = 0; if (isSanityConfigured) [articles, authors, total] = await Promise.all([client.fetch(FILTERED_ARTICLES_QUERY, { pillar: pillar ?? null, author: author ?? null, start, end: start + perPage }) as Promise<Article[]>, client.fetch(NEWSROOM_AUTHORS_QUERY) as Promise<Author[]>, client.fetch(FILTERED_ARTICLES_COUNT_QUERY, { pillar: pillar ?? null, author: author ?? null }) as Promise<number>]); const pages = Math.max(1, Math.ceil(total / perPage)); const href = (next: number) => `/articles?${new URLSearchParams({ ...(pillar ? { pillar } : {}), ...(author ? { author } : {}), page: String(next) })}`; return <main className="px-6 py-10 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><Link href="/news" className="text-sm font-medium text-indigo-600 hover:text-slate-950">← Back to newsroom</Link><h1 className="mt-6 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">All articles</h1><p className="mt-3 max-w-2xl text-lg text-slate-600">Browse the complete newsroom by category or author.</p><form className="mt-8 grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-[1fr_1fr_auto]" action="/articles" method="get"><select name="pillar" defaultValue={pillar || ""} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">All categories</option>{contentPillars.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</select><select name="author" defaultValue={author || ""} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">All authors</option>{authors.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><button className="rounded-xl bg-slate-950 px-5 py-2 text-sm font-medium text-white hover:bg-indigo-700">Apply filters</button></form>{articles.length ? <div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{articles.map((article) => <Card key={article._id} article={article} />)}</div> : <p className="mt-10 text-slate-600">No published articles match those filters.</p>}{pages > 1 ? <nav className="mt-10 flex items-center gap-3">{page > 1 ? <Link href={href(page - 1)} className="rounded-full border border-slate-200 px-4 py-2 text-sm">Previous</Link> : null}<span className="text-sm text-slate-500">Page {page} of {pages}</span>{page < pages ? <Link href={href(page + 1)} className="rounded-full border border-slate-200 px-4 py-2 text-sm">Next</Link> : null}</nav> : null}</div></main>; }
